USERNAME = "naoh.enjoyer"
PROFILES = ["daquan", "sarcasm_only", "funny_videos", "_eldanko_", "bruhifunny", "kermitsbrokenmemes", "dank_meme_bandit"]
SUBREDDITS = ["shitposting", "discordvideos"]
DOWNLOAD_PATH = "downloaded_memes"
OUTPUT_PATH = "Fine memes ☕️ #shorts #memes.mp4"
TOLERANCE = 25
MAX_DURATION = 45
MAX_HEIGHT = 1920
ASPECT_RATIO = 9 / 16