USERNAME = "naoh.enjoyer"
PROFILES = ["daquan", "sarcasm_only", "funny_videos", "_eldanko_", "bruhifunny", "kermitsbrokenmemes", "dank_meme_bandit"]
DOWNLOAD_PATH = "downloaded_memes"
OUTPUT_PATH = "compilation.mp4"
TOLERANCE = 30
MAX_DURATION = 55
MAX_HEIGHT = 1920
ASPECT_RATIO = 9 / 16
TITLE = "Fine memes ☕️"
TAGS = ["shorts", "memes"]
DESCRIPTION = ":)"