USERNAME = ""
PROFILES = []
SUBREDDITS = []
DOWNLOAD_PATH = ""
OUTPUT_PATH = ""
TOLERANCE = 25
MAX_DURATION = 45
MAX_HEIGHT = 1920
ASPECT_RATIO = 9 / 16
ASPECT_RATIO_LIMIT = 4 / 5

USE_INSTAGRAM = True
USE_REDDIT = True